In [25]:
import numpy as np 
import pandas as pd

## Creating a Dataframe

In [26]:
data = {
    'Name':['John','Anna',"Peter","Linda"],
    "Age":[28,34,29,42],
    'City':["Newyork","Paris","Berlin","London"],
    'Salary':[65000,70000,62000,85000]
}

df = pd.DataFrame(data)

In [27]:
data_list = [
    ['John',28,'York',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000],
]

columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns=columns)
df2

    Name  Age    City  Salary
0   John   28    York   65000
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

## Selecting and Indexing of COlumns

In [28]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [29]:
df2[['City',"Name"]]

     City   Name
0    York   John
1   Paris   Anna
2  Berlin  Peter
3  London  Linda

## Creating a new column

In [30]:
df2["Designation"] = ["Doctor",'Engineer','DOctor','Eng.']

In [31]:
df2

    Name  Age    City  Salary Designation
0   John   28    York   65000      Doctor
1   Anna   34   Paris   70000    Engineer
2  Peter   29  Berlin   62000      DOctor
3  Linda   42  London   85000        Eng.

## Removing COlumns

In [32]:
df2.drop(['Salary','City'],axis=1,inplace=True)

In [33]:
df2

    Name  Age Designation
0   John   28      Doctor
1   Anna   34    Engineer
2  Peter   29      DOctor
3  Linda   42        Eng.

In [34]:
df2.drop(0,axis = 0)

    Name  Age Designation
1   Anna   34    Engineer
2  Peter   29      DOctor
3  Linda   42        Eng.

In [35]:
df2.loc[0]

Name             John
Age                28
Designation    Doctor
Name: 0, dtype: object

In [36]:
df2.iloc[3]

Name           Linda
Age               42
Designation     Eng.
Name: 3, dtype: object


# Selecting Subsets of Rows and COlumns

In [37]:
df.loc[[0,1],["City","Salary"]]

      City  Salary
0  Newyork   65000
1    Paris   70000

In [38]:
df

    Name  Age     City  Salary
0   John   28  Newyork   65000
1   Anna   34    Paris   70000
2  Peter   29   Berlin   62000
3  Linda   42   London   85000

In [41]:
df.loc[[2,3],["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

## conditional Selection

In [ ]:
df

    name  Age     City  Salary
0   John   28  Newyork   65000
1   Anna   34    Paris   70000
2  Peter   29   Berlin   62000
3  Linda   42   London   85000

In [43]:
df[df["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [46]:
df[(df["Age"]>30) & (df["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000